# 02_flume_agent.conf
# This is the Apache Flume configuration file to ingest the massive 15GB log file into HDFS.

# Name the components on this agent
LogAgent.sources = SpoolDirSource
LogAgent.channels = MemChannel
LogAgent.sinks = HDFSSink

# Describe/configure the source
# Define the Source
LogAgent.sources.SpoolDirSource.type = exec
LogAgent.sources.SpoolDirSource.command = powershell.exe -NoProfile -Command "Get-Content data\live_website.log -Wait"
# To handle extremely large files efficiently
LogAgent.sources.SpoolDirSource.deserializer.maxLineLength = 10000
LogAgent.sources.SpoolDirSource.batchSize = 1000

# Describe the sink
# We write the ingested logs directly to HDFS
LogAgent.sinks.HDFSSink.type = hdfs
LogAgent.sinks.HDFSSink.hdfs.path = hdfs://localhost:9000/flume/events/
LogAgent.sinks.HDFSSink.hdfs.filePrefix = events-
LogAgent.sinks.HDFSSink.hdfs.inUsePrefix = .
LogAgent.sinks.HDFSSink.hdfs.round = false
LogAgent.sinks.HDFSSink.hdfs.useLocalTimeStamp = true

# HDFS optimization for testing
LogAgent.sinks.HDFSSink.hdfs.rollSize = 134217728
LogAgent.sinks.HDFSSink.hdfs.rollCount = 0
LogAgent.sinks.HDFSSink.hdfs.rollInterval = 15
LogAgent.sinks.HDFSSink.hdfs.fileType = DataStream
LogAgent.sinks.HDFSSink.hdfs.writeFormat = Text

# Use a channel which buffers events in memory
LogAgent.channels.MemChannel.type = memory
LogAgent.channels.MemChannel.capacity = 100000
LogAgent.channels.MemChannel.transactionCapacity = 10000

# Bind the source and sink to the channel
LogAgent.sources.SpoolDirSource.channels = MemChannel
LogAgent.sinks.HDFSSink.channel = MemChannel
